import { z } from "zod";
import {
  saySchema,
  menuSchema,
  inputSchema,
  notifySchema,
  nvlSchema,
  characterSchema,
  waitSchema,
  pauseSchema,
  randomSchema,
  jumpSchema,
  navigateSchema,
  funcSchema,
  callSchema,
  returnSchema,
  ifSchema,
  whileSchema,
  forSchema,
  foreachSchema,
  switchSchema,
  emptySchema,
  assertSchema,
  guardSchema,
  assignSchema,
  undefSchema,
  arraySchema,
  arrayPushSchema,
  arrayPopSchema,
  dictSchema,
  dictSetSchema,
  saveSchema,
  loadSchema,
  autoSaveSchema,
  saveDeleteSchema,
  bgmSchema,
  stopSchema,
  seSchema,
  voiceSchema,
  videoSchema,
  cutsceneSchema,
  seekVideoSchema,
  videoSkipableSchema,
  minigameSchema,
  interactionSchema,
  showSchema,
  hideSchema,
  backgroundSchema,
  bgSwitchSchema,
  zindexSchema,
  styleSchema,
  windowSchema,
  animateSchema,
  animateBlockSchema,
  transitionSchema,
  shakeSchema,
  textTypewriterSchema,
} from "./commands";

/** op → 负载 schema（不含 op 键本身）；字面量键形态 = `ScriptCommand` 判别联合的派生源。
 * 新增 op = 加条目 = 表单 / 校验 / 类型三面自动出现（单一事实源，零重复定义） */
export const OP_SCHEMA_MAP = {
  say: saySchema,
  menu: menuSchema,
  input: inputSchema,
  notify: notifySchema,
  nvl: nvlSchema,
  character: characterSchema,
  wait: waitSchema,
  pause: pauseSchema,
  random: randomSchema,
  jump: jumpSchema,
  navigate: navigateSchema,
  func: funcSchema,
  call: callSchema,
  return: returnSchema,
  if: ifSchema,
  while: whileSchema,
  for: forSchema,
  foreach: foreachSchema,
  switch: switchSchema,
  break: emptySchema,
  continue: emptySchema,
  assert: assertSchema,
  guard: guardSchema,
  set: assignSchema,
  define: assignSchema,
  let: assignSchema,
  local: assignSchema,
  undef: undefSchema,
  array: arraySchema,
  array_push: arrayPushSchema,
  array_pop: arrayPopSchema,
  dict: dictSchema,
  dict_set: dictSetSchema,
  save: saveSchema,
  load: loadSchema,
  auto_save: autoSaveSchema,
  save_delete: saveDeleteSchema,
  bgm: bgmSchema,
  stop_bgm: stopSchema,
  se: seSchema,
  ambient: bgmSchema,
  stop_ambient: stopSchema,
  voice: voiceSchema,
  stop_voice: stopSchema,
  video: videoSchema,
  cutscene: cutsceneSchema,
  seek_video: seekVideoSchema,
  pause_video: emptySchema,
  resume_video: emptySchema,
  stop_video: emptySchema,
  video_skipable: videoSkipableSchema,
  minigame: minigameSchema,
  interaction: interactionSchema,
  // 元素系统
  show: showSchema,
  hide: hideSchema,
  background: backgroundSchema,
  bg_switch: bgSwitchSchema,
  zindex: zindexSchema,
  style: styleSchema,
  window: windowSchema,
  animate: animateSchema,
  animate_block: animateBlockSchema,
  transition: transitionSchema,
  shake: shakeSchema,
  text_typewriter: textTypewriterSchema,
};

/** 运行期查找面（与 `OP_SCHEMA_MAP` 同一对象，键集恒等）；新增 op 自动可用 */
export const OP_SCHEMAS: Readonly<Record<string, z.ZodType>> = OP_SCHEMA_MAP;
