import type { CellScan } from "./types";

/** 生成物渲染（逐字节确定：同扫描同文本；入库文件，手改会被覆盖） */
export function renderFunRegister(scan: CellScan): string {
  const lines: string[] = [];
  lines.push("/* GENERATED by stories:build (cell) — 手改会在下次构建被覆盖 */");
  // Record<string, GuardFn> 给字面量参数提供语境类型（strict 下无 implicit-any）
  lines.push('import type { GuardFn } from "@lingfan/engine";');
  for (const statement of scan.importStatements) lines.push(statement);
  lines.push("");
  lines.push("/** 故事源 cell 提取出的具名守卫注册表：宿主 `import { guards }` 直接传给引擎，零手写接入。 */");
  lines.push("export const guards: Record<string, GuardFn> = {");
  for (const guardEntry of scan.guards) {
    lines.push(`  ${JSON.stringify(guardEntry.name)}: ${guardEntry.implText},`);
  }
  lines.push("};");
  lines.push("");
  lines.push("/** 守卫名的构建期登记处：故事源 `guard(name)` 引用了未登记的名字会在类型期报错。 */");
  lines.push('declare module "@lingfan/editor" {');
  lines.push("  interface GuardNameRegistry {");
  for (const guardEntry of scan.guards) {
    lines.push(`    ${JSON.stringify(guardEntry.name)}: 1;`);
  }
  lines.push("  }");
  lines.push("}");
  return `${lines.join("\n")}\n`;
}
