/**
 * 06-D2 op 目录：op 标签/分组 + 字段呈现语义（label/kind）。
 * 字段的类型/必填/可选值/默认值以 opSchemas（Zod）为唯一事实源——本文件只承载
 * 呈现与诊断语义元数据，字段名集合与 schema 由互锁测试锁定（schema.test.ts）。
 * 字段语义以执行器为权威（packages/engine/src/runtime/engine.ts）。
 * 锚点: schema-driven-forms
 */

import type { FieldKind, OpMeta } from "../contracts";

export const OP_META: readonly OpMeta[] = [
  { op: "say", label: "对话", group: "narrative" },
  { op: "menu", label: "选项", group: "narrative" },
  { op: "input", label: "输入", group: "narrative" },
  { op: "notify", label: "通知", group: "narrative" },
  { op: "nvl", label: "NVL 模式", group: "presentation" },
  { op: "character", label: "角色定义", group: "presentation" },
  { op: "wait", label: "等待", group: "flow" },
  { op: "pause", label: "暂停", group: "flow" },
  { op: "random", label: "随机数", group: "flow" },
  { op: "jump", label: "跳转", group: "flow" },
  { op: "navigate", label: "导航", group: "flow" },
  { op: "call", label: "调用函数", group: "flow" },
  { op: "return", label: "函数返回", group: "flow" },
  { op: "if", label: "条件分支", group: "flow" },
  { op: "while", label: "循环", group: "flow" },
  { op: "for", label: "遍历循环", group: "flow" },
  { op: "foreach", label: "集合迭代", group: "flow" },
  { op: "switch", label: "多路分支", group: "flow" },
  { op: "break", label: "跳出循环", group: "flow" },
  { op: "continue", label: "下一轮循环", group: "flow" },
  { op: "set", label: "赋值", group: "variables" },
  { op: "define", label: "全局定义", group: "variables" },
  { op: "let", label: "块级变量", group: "variables" },
  { op: "local", label: "块级变量", group: "variables" },
  { op: "undef", label: "销毁变量", group: "variables" },
  { op: "array", label: "数组定义", group: "variables" },
  { op: "array_push", label: "数组追加", group: "variables" },
  { op: "array_pop", label: "数组弹出", group: "variables" },
  { op: "dict", label: "字典定义", group: "variables" },
  { op: "dict_set", label: "字典写入", group: "variables" },
  { op: "save", label: "存档", group: "save" },
  { op: "load", label: "读档", group: "save" },
  { op: "auto_save", label: "自动存档开关", group: "save" },
  { op: "save_delete", label: "删除存档", group: "save" },
  { op: "bgm", label: "背景乐", group: "audio" },
  { op: "stop_bgm", label: "停止背景乐", group: "audio" },
  { op: "se", label: "音效", group: "audio" },
  { op: "ambient", label: "环境音", group: "audio" },
  { op: "stop_ambient", label: "停止环境音", group: "audio" },
  { op: "voice", label: "语音", group: "audio" },
  { op: "stop_voice", label: "停止语音", group: "audio" },
  { op: "video", label: "视频", group: "video" },
  { op: "cutscene", label: "过场", group: "video" },
  { op: "seek_video", label: "视频跳转", group: "video" },
  { op: "pause_video", label: "视频暂停", group: "video" },
  { op: "resume_video", label: "视频恢复", group: "video" },
  { op: "stop_video", label: "停止视频", group: "video" },
  { op: "video_skipable", label: "视频可跳开关", group: "video" },
  { op: "minigame", label: "小游戏", group: "minigame" },
];

interface FieldMeta {
  label: string;
  kind: FieldKind;
}

/**
 * 字段元数据：键 = `<op>.<字段路径>`；嵌套项内字段以 `[]` 标注项路径
 * （如 menu.options[].text）。kind 语义见 contracts/forms.ts FieldKind。
 */
export const FIELD_META: Readonly<Record<string, FieldMeta>> = {
  "say.text": { label: "文本", kind: "text" },
  "say.speaker": { label: "说话人", kind: "text" },
  "say.clickable": { label: "点击后继续", kind: "boolean" },
  "say.noskip": { label: "禁止跳过", kind: "boolean" },
  "say.instant": { label: "瞬间显示", kind: "boolean" },
  "say.typewriter": { label: "打字机速度", kind: "number" },
  "say.voice": { label: "本句语音", kind: "resource" },
  "say.template": { label: "对话框模板", kind: "string" },
  "menu.prompt": { label: "提示语", kind: "text" },
  "menu.options": { label: "选项", kind: "array" },
  "menu.options[].text": { label: "选项文本", kind: "text" },
  "menu.options[].target": { label: "目标列", kind: "identifier" },
  "input.prompt": { label: "提示语", kind: "text" },
  "input.store": { label: "存入变量", kind: "identifier" },
  "notify.text": { label: "文本", kind: "text" },
  "notify.type": { label: "类型", kind: "string" },
  "notify.duration": { label: "时长（毫秒）", kind: "number" },
  "nvl.mode": { label: "模式", kind: "enum" },
  "character.key": { label: "角色键", kind: "identifier" },
  "character.name": { label: "显示名", kind: "text" },
  "character.color": { label: "颜色", kind: "string" },
  "character.size": { label: "字号", kind: "string" },
  "character.font": { label: "字体", kind: "string" },
  "character.textColor": { label: "文字颜色", kind: "string" },
  "character.screen": { label: "对话框模板", kind: "string" },
  "wait.seconds": { label: "秒数", kind: "number" },
  "wait.skipable": { label: "可跳过", kind: "boolean" },
  "pause.seconds": { label: "秒数", kind: "number" },
  "random.seed": { label: "种子", kind: "integer" },
  "random.range": { label: "范围 [min, max]", kind: "tuple" },
  "random.var": { label: "写入变量", kind: "identifier" },
  "jump.target": { label: "目标列", kind: "identifier" },
  "navigate.path": { label: "路径/列", kind: "identifier" },
  "navigate.scene": { label: "场景列", kind: "identifier" },
  "call.target": { label: "函数名", kind: "identifier" },
  "call.args": { label: "实参", kind: "array" },
  "return.value": { label: "返回值", kind: "value" },
  "if.cond": { label: "条件", kind: "expression" },
  "if.then": { label: "则", kind: "body" },
  "if.elif": { label: "否则如果", kind: "array" },
  "if.elif[].cond": { label: "条件", kind: "expression" },
  "if.elif[].then": { label: "则", kind: "body" },
  "if.else": { label: "否则", kind: "body" },
  "while.cond": { label: "条件", kind: "expression" },
  "while.body": { label: "循环体", kind: "body" },
  "for.var": { label: "循环变量", kind: "identifier" },
  "for.in": { label: "序列表达式", kind: "expression" },
  "for.body": { label: "循环体", kind: "body" },
  "foreach.var": { label: "元素变量", kind: "identifier" },
  "foreach.key": { label: "集合变量", kind: "identifier" },
  "foreach.body": { label: "循环体", kind: "body" },
  "switch.on": { label: "分支表达式", kind: "expression" },
  "switch.cases": { label: "分支", kind: "array" },
  "switch.cases[].value": { label: "匹配值", kind: "value" },
  "switch.cases[].body": { label: "分支体", kind: "body" },
  "switch.default": { label: "缺省分支", kind: "body" },
  "set.key": { label: "变量名", kind: "identifier" },
  "set.value": { label: "值", kind: "value" },
  "define.key": { label: "变量名", kind: "identifier" },
  "define.value": { label: "值", kind: "value" },
  "let.key": { label: "变量名", kind: "identifier" },
  "let.value": { label: "值", kind: "value" },
  "local.key": { label: "变量名", kind: "identifier" },
  "local.value": { label: "值", kind: "value" },
  "undef.key": { label: "变量名", kind: "identifier" },
  "array.key": { label: "变量名", kind: "identifier" },
  "array.items": { label: "初始项", kind: "array" },
  "array.once": { label: "已存在时跳过", kind: "boolean" },
  "array_push.key": { label: "目标数组", kind: "identifier" },
  "array_push.value": { label: "值", kind: "value" },
  "array_pop.key": { label: "目标数组", kind: "identifier" },
  "dict.key": { label: "变量名", kind: "identifier" },
  "dict.value": { label: "初始字段", kind: "object" },
  "dict.once": { label: "已存在时跳过", kind: "boolean" },
  "dict_set.key": { label: "目标字典", kind: "identifier" },
  "dict_set.field": { label: "字段名", kind: "identifier" },
  "dict_set.value": { label: "值", kind: "value" },
  "save.slot": { label: "槽位", kind: "identifier" },
  "save.title": { label: "标题", kind: "text" },
  "load.slot": { label: "槽位", kind: "identifier" },
  "auto_save.enabled": { label: "启用", kind: "boolean" },
  "save_delete.slot": { label: "槽位", kind: "identifier" },
  "bgm.resource": { label: "资源", kind: "resource" },
  "bgm.volume": { label: "音量", kind: "number" },
  "bgm.loop": { label: "循环", kind: "boolean" },
  "bgm.fade": { label: "淡入（毫秒）", kind: "number" },
  "bgm.restart": { label: "回起点重播", kind: "boolean" },
  "stop_bgm.fade": { label: "淡出（毫秒）", kind: "number" },
  "se.resource": { label: "资源", kind: "resource" },
  "se.volume": { label: "音量", kind: "number" },
  "ambient.resource": { label: "资源", kind: "resource" },
  "ambient.volume": { label: "音量", kind: "number" },
  "ambient.loop": { label: "循环", kind: "boolean" },
  "ambient.fade": { label: "淡入（毫秒）", kind: "number" },
  "ambient.restart": { label: "回起点重播", kind: "boolean" },
  "stop_ambient.fade": { label: "淡出（毫秒）", kind: "number" },
  "voice.resource": { label: "资源", kind: "resource" },
  "voice.volume": { label: "音量", kind: "number" },
  "voice.auto_stop": { label: "推进即停", kind: "boolean" },
  "voice.restart": { label: "回起点重播", kind: "boolean" },
  "stop_voice.fade": { label: "淡出（毫秒）", kind: "number" },
  "video.resource": { label: "资源", kind: "resource" },
  "video.volume": { label: "音量", kind: "number" },
  "video.loop": { label: "循环", kind: "boolean" },
  "cutscene.resource": { label: "资源", kind: "resource" },
  "cutscene.volume": { label: "音量", kind: "number" },
  "cutscene.skipable": { label: "可跳过", kind: "boolean" },
  "seek_video.seconds": { label: "目标秒数", kind: "number" },
  "video_skipable.value": { label: "启用", kind: "boolean" },
  "minigame.game": { label: "游戏 ID", kind: "identifier" },
  "minigame.config": { label: "配置", kind: "object" },
  "minigame.on_success": { label: "成功跳转列", kind: "identifier" },
  "minigame.on_fail": { label: "失败跳转列", kind: "identifier" },
  "minigame.reward": { label: "奖励", kind: "array" },
  "minigame.reward[].key": { label: "奖励变量", kind: "identifier" },
  "minigame.reward[].value": { label: "奖励值", kind: "value" },
};

/** 文本插值面（诊断扫描用）：text kind 字段集合的查询入口 */
export function fieldMetaOf(key: string): FieldMeta | undefined {
  return FIELD_META[key];
}
